import { JSDOM } from 'jsdom';
import { readFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE || '/kien-thuc/';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function load(path,mobile=false){const html=await readFile(`dist/${path}index.html`,'utf8');const dom=new JSDOM(html,{runScripts:'outside-only',url:`https://example.invalid${base}${path}`,pretendToBeVisual:true});const w=dom.window;w.matchMedia=()=>({matches:mobile,addEventListener(){}});w.IntersectionObserver=class{observe(){}};const original=w.setTimeout.bind(w);w.setTimeout=(fn)=>original(fn,1);for(const script of w.document.querySelectorAll('script')){assert.equal(script.hasAttribute('src'),false,'Update test to resolve external JS assets');w.eval(`(()=>{${script.textContent}\n})()`);}return dom;}
for(const path of ['', 'thiet-ke/auto-layout/']){
const dom=await load(path);const d=dom.window.document;
assert.equal(d.documentElement.lang,'vi');assert.equal(d.querySelectorAll('h1').length,1);
for(const element of d.querySelectorAll('a[href],link[href]')){const href=element.getAttribute('href');if(href.startsWith('#')){assert.ok(d.getElementById(href.slice(1)),`Missing section ${href}`);continue;}assert.ok(href.startsWith(base),`Not base aware: ${href}`);let local=href.slice(base.length);if(local.endsWith('/')||local==='')local+='index.html';await access(resolve('dist',local));}
const search=d.querySelector('#lesson-search');search.value='thiet ke';search.dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelectorAll('[data-search]:not([hidden])').length,1);search.value='zzzz';search.dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelector('#search-empty').hidden,false);search.value='';search.dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelectorAll('[data-search]:not([hidden])').length,2);
if(!path){const button=d.querySelector('#simulate');button.click();assert.equal(button.disabled,true);button.click();await wait(60);assert.equal(d.querySelectorAll('.pipeline .complete').length,4);assert.equal(button.disabled,false);button.click();await wait(60);assert.match(d.querySelector('#simulation-status').textContent,/Hoàn tất/);}else{d.querySelector('input[value="column"]').checked=true;d.querySelector('#gap').value='32';d.querySelector('#padding').value='40';d.querySelector('#gap').dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.equal(d.querySelector('#demo-frame').style.flexDirection,'column');assert.equal(d.querySelector('#demo-frame').style.gap,'32px');assert.match(d.querySelector('#css-output').textContent,/padding: 40px/);d.querySelector('#reset-layout').click();assert.equal(d.querySelector('#gap').value,'16');assert.equal(d.querySelector('#demo-frame').style.flexDirection,'row');}
dom.window.close();
}
const mobile=await load('',true);const d=mobile.window.document;assert.equal(d.querySelector('#sidebar').inert,true);d.querySelector('#menu-toggle').click();assert.equal(d.querySelector('#sidebar').inert,false);assert.equal(d.activeElement.id,'lesson-search');d.dispatchEvent(new mobile.window.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.querySelector('#menu-toggle').getAttribute('aria-expanded'),'false');assert.equal(d.activeElement.id,'menu-toggle');d.querySelector('#menu-toggle').click();d.querySelector('#nav-backdrop').click();assert.equal(d.querySelector('#sidebar').inert,true);mobile.window.close();
console.log(`PASS DOM tests (${base}): both lessons, internal links/assets/anchors, accent-insensitive search/empty state/reset, simulation/replay, controls/reset, mobile open/Escape/backdrop. Layout and real-browser behavior NOT validated.`);
